#!/system/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="scull"
device="scull"
mode="664"

/system/bin/insmod /system/lib/$module.ko || exit 1

# retrieve major number
major=$(awk '$2=="'$module'" {print $1}' /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
chmod $mode  /dev/${device}[0-3]

rm /dev/${device}pipe[0-3]
mknod /dev/${device}pipe0 c $major 4
mknod /dev/${device}pipe1 c $major 5
mknod /dev/${device}pipe2 c $major 6
mknod /dev/${device}pipe3 c $major 7
chmod $mode  /dev/${device}pipe[0-3]

rm /dev/${device}single
mknod /dev/${device}single  c $major 8
chmod $mode  /dev/${device}single

rm /dev/${device}uid
mknod /dev/${device}uid   c $major 9
chmod $mode  /dev/${device}uid

rm /dev/${device}wuid
mknod /dev/${device}wuid  c $major 10
chmod $mode  /dev/${device}wuid

rm /dev/${device}priv
mknod /dev/${device}priv  c $major 11
chmod $mode  /dev/${device}priv

