#!/system/bin/sh
module="scull"
device="scull"

/system/bin/rmmod $module || exit 1

# Remove stale nodes

rm /dev/${device}[0-3] 
rm /dev/${device}priv
rm /dev/${device}pipe[0-3]
rm /dev/${device}single
rm /dev/${device}uid
rm /dev/${device}wuid





